import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AppTheme } from "@/components/ui/theme/AppTheme";
import { ThemeProvider } from "next-themes";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Spomov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        {children}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AppTheme />
        </ThemeProvider>
      </body>
    </html>
  );
}
